namespace: nginx

deployment:
  name: nginx-deployment
  replicas: 1
  image: nginx:latest
  containerPort: 80
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

service:
  name: nginx-service
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

hpa:
  name: nginx-hpa
  minReplicas: 2
  maxReplicas: 5
  averageUtilization: 50

networkPolicy:
  name: nginx-allow-same-namespace
